### ISSUE TITLE
MissingPluginException while using within widget test

### ISSUE THREAD

**Issue by thedejifab** [MisterJimson/flutter_keyboard_visibility#31]
When I try to use plugin within my widget test, although my tests do not fall and the golden test snapshots shows that the effect of setting keyboard visibility for testing is at play, I still get the MissingPluginException below in my logs. I've tried reloading, updating packages and all of that but it doesn't seem to be working.

```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
flutter_keyboard_visibility:
MissingPluginException(No implementation found for method listen on channel
flutter_keyboard_visibility)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:519:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:505:64)
#8      KeyboardVisibility.onChange (package:flutter_keyboard_visibility/flutter_keyboard_visibility.dart:22:12)
#9      _KeyboardVisibilityProviderState.initState (package:flutter_keyboard_visibility/flutter_keyboard_visibility.dart:116:28)
#10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
#14     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
#15     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1126:5)
#16     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1140:7)
#17     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
#18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
#19     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1006:18)
#20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
#21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
#22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
#23     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:879:9)
#26     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#27     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:866:27)
#28     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:441:22)
#31     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
#32     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:438:27)
#35     AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:921:22)
#38     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:919:26)
#39     WidgetTester.runAsync (package:flutter_test/src/widget_tester.dart:571:17)
#42     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:140:29)
#55     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1099:17)
#56     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1087:35)
(elided 37 frames from class _FakeAsync, dart:async, and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by PaoloDooM** [comment]
> 
> 
> When I try to use plugin within my widget test, although my tests do not fall and the golden test snapshots shows that the effect of setting keyboard visibility for testing is at play, I still get the MissingPluginException below in my logs. I've tried reloading, updating packages and all of that but it doesn't seem to be working.
> 
> ```
> ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
> The following MissingPluginException was thrown while activating platform stream on channel
> flutter_keyboard_visibility:
> MissingPluginException(No implementation found for method listen on channel
> flutter_keyboard_visibility)
> 
> When the exception was thrown, this was the stack:
> #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
> <asynchronous suspension>
> #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
> #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:519:29)
> #3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:505:64)
> #8      KeyboardVisibility.onChange (package:flutter_keyboard_visibility/flutter_keyboard_visibility.dart:22:12)
> #9      _KeyboardVisibilityProviderState.initState (package:flutter_keyboard_visibility/flutter_keyboard_visibility.dart:116:28)
> #10     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
> #11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
> #12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
> #13     Element.updateChild (package:flutter/src/widgets/framework.dart:3211:20)
> #14     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1148:16)
> #15     RenderObjectToWidgetElement.update (package:flutter/src/widgets/binding.dart:1126:5)
> #16     RenderObjectToWidgetElement.performRebuild (package:flutter/src/widgets/binding.dart:1140:7)
> #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4218:5)
> #18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2627:33)
> #19     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1006:18)
> #20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:284:5)
> #21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1113:15)
> #22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1052:9)
> #23     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:879:9)
> #26     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
> #27     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:866:27)
> #28     WidgetTester.pumpWidget.<anonymous closure> (package:flutter_test/src/widget_tester.dart:441:22)
> #31     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:72:41)
> #32     WidgetTester.pumpWidget (package:flutter_test/src/widget_tester.dart:438:27)
> #35     AutomatedTestWidgetsFlutterBinding.runAsync.<anonymous closure> (package:flutter_test/src/binding.dart:921:22)
> #38     AutomatedTestWidgetsFlutterBinding.runAsync (package:flutter_test/src/binding.dart:919:26)
> #39     WidgetTester.runAsync (package:flutter_test/src/widget_tester.dart:571:17)
> #42     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:140:29)
> #55     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1099:17)
> #56     AutomatedTestWidgetsFlutterBinding.runTest.<anonymous closure> (package:flutter_test/src/binding.dart:1087:35)
> (elided 37 frames from class _FakeAsync, dart:async, and package:stack_trace)
> ════════════════════════════════════════════════════════════════════════════════════════════════════
> ```

im having the same issue in flutter stable v1.17.4

**Comment by JanezStupar** [comment]
Same issue. Linux desktop. Appears on build.

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.21.0-6.0.pre.91, on Linux, locale en_US.UTF-8)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, set ANDROID_SDK_ROOT to that location.
      You may also want to add it to your PATH environment variable.

[✓] Linux toolchain - develop for Linux desktop
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.3)
[✓] Connected device (1 available)
```

```
An Observatory debugger and profiler on Linux is available at: http://127.0.0.1:35943/8Hu9VfvER-I=/
flutter: ══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
flutter: The following MissingPluginException was thrown while activating platform stream on channel
flutter: flutter_keyboard_visibility:                            
flutter: MissingPluginException(No implementation found for method listen on channel
flutter: flutter_keyboard_visibility)                      
flutter:                                                                     
flutter: When the exception was thrown, this was the stack:
flutter: #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
flutter: <asynchronous suspension>                                                                                                                            
flutter: #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
flutter: #2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:542:29)
flutter: #3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:528:64)
flutter: #8      KeyboardVisibility.onChange (package:flutter_keyboard_visibility/flutter_keyboard_visibility.dart:22:12)
flutter: #9      new _TypeAheadFieldState (package:flutter_typeahead/flutter_typeahead.dart:729:63)
flutter: #10     TypeAheadField.createState (package:flutter_typeahead/flutter_typeahead.dart:704:44)
flutter: #11     new StatefulElement (package:flutter/src/widgets/framework.dart:4652:25)
flutter: #12     StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:904:38)
flutter: ...     Normal element mounting (58 frames)
flutter: #70     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3507:14)
flutter: #71     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6008:32)
flutter: ...     Normal element mounting (28 frames)
flutter: #99     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3507:14)
flutter: #100    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6008:32)
flutter: ...     Normal element mounting (216 frames)
flutter: #316    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3507:14)
flutter: #317    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6008:32)
flutter: ...     Normal element mounting (273 frames)
flutter: #590    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3507:14)
flutter: #591    Element.updateChild (package:flutter/src/widgets/framework.dart:3266:18)
flutter: #592    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1219:16)
flutter: #593    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1190:5)
flutter: #594    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1132:17)
flutter: #595    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2626:19)
flutter: #596    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1131:13)
flutter: #597    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:941:7)
flutter: #598    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:922:7)
flutter: (elided 15 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
```

**Comment by zkx2020** [comment]
same bug...

**Comment by GP4cK** [comment]
If you add this to the `main()` of your test file, that should get rid of the exception message:

```dart 
void main() {
  // mock method channel handler
  const channel = MethodChannel('flutter_keyboard_visibility');

  setUp(() async {
    const dummyInteger = 1;

    channel.setMockMethodCallHandler((MethodCall methodCall) async {
      await ServicesBinding.instance.defaultBinaryMessenger.handlePlatformMessage(
        'flutter_keyboard_visibility',
        const StandardMethodCodec().encodeSuccessEnvelope(dummyInteger),
        (ByteData data) {},
      );
    });
  });
```

**Comment by MisterJimson** [comment]
Just opened a PR that makes it so the library will no longer throw `MissingPluginException` if you call `KeyboardVisibility.setVisibilityForTesting(value)` first. Will merge soon.

**Comment by MisterJimson** [comment]
Fixed in 3.2.2 as in above comment

**Comment by tashiwangdi** [comment]
We still see this issue when running a widget test that has got nothing to do with the plugin: 

`══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following MissingPluginException was thrown while activating platform stream on channel
flutter_keyboard_visibility:
MissingPluginException(No implementation found for method listen on channel
flutter_keyboard_visibility)`

**Comment by MisterJimson** [comment]
Are you setting a value using `KeyboardVisibility.setVisibilityForTesting`? That will prevent the native code from trying to execute.

**Comment by tashiwangdi** [comment]
Thank you. Tried that and it helped.

**Comment by GP4cK** [comment]
> Are you setting a value using `KeyboardVisibility.setVisibilityForTesting`? That will prevent the native code from trying to execute.

Just a note: it's `KeyboardVisibilityTesting.setVisibilityForTesting(false)`
